config/routes.rb
Rails.application.routes.draw do
  root "events#index"

  devise_for :users, 
  path: 'auth', 
  path_names: {
     sign_in: 'login',
     sign_out: 'logout',
     password: 'secret',
     confirmation: 'verification',
     unlock: 'unblock',
     registration: 'register',
     sign_up: 'signup' 
    },
    controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations' }
        
  resources :events
  post 'events/:id/guests', to: 'events#add_guest', as: :add_guest
  delete 'events/:id/guests', to: 'events#remove_guest', as: :remove_guest
  get 'profiles/:username', to: 'profiles#show', as: :show_profile
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  has_many :event_attendings, foreign_key: :event_with_guest_id
  has_many :guests, through: :event_attendings
  belongs_to :host, class_name: "User"

  scope :incoming, -> { where('start_time > now()') }
  scope :overdue, -> { where('start_time < now()') }

  validates_comparison_of :start_time, less_than: :end_time
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create show edit update delete add_guest remove_guest]

  def index
    search_params = allowed_event_search_params

    if search_params[:search_name].present?
      @events = Event.where('lower(name) like ?', "%#{search_params[:search_name]}%".downcase).order(created_at: :desc)
      @search_name = search_params[:search_name]
    else
      @events = Event.all.order(created_at: :desc)
      @search_name = ""
    end
  end

  def show
    @event = Event.find(params[:id]) or not_found
  end

  def new
    @event = Event.new
    search_user_handler()
  end

  def edit
    @event = Event.find(params[:id]) or not_found
    search_user_handler()
  end

  def update
    @event = Event.find(params[:id]) or not_found
    event_params = allowed_event_params
    event_params[:start_time] = modify_datetime(event_params[:start_time].to_datetime , allowed_timezone_params[:time_zone])
    event_params[:end_time] = modify_datetime(event_params[:end_time].to_datetime , allowed_timezone_params[:time_zone])

    respond_to do |format|
      if @event.update(event_params)
        @event.guest_ids = allowed_guest_params[:guest_ids]
        format.html { redirect_to(@event,
                      :notice => 'This event was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors,
                      :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @event = Event.find(params[:id]) or not_found
    @event.destroy
  
    respond_to do |format|
      format.html { redirect_to(events_path) }
      format.xml  { head :ok }
    end
  end

  def create
    @event = current_user.events.build(allowed_event_params)
    if allowed_guest_params[:guest_ids].include?(@event.host.id)
      flash.now[:error] = 'Something\'s wrong. Can\'t create new event. Please check your input'
      render :new, status: :unprocessable_entity
    else
      @event.start_time = modify_datetime(@event.start_time, allowed_timezone_params[:time_zone])
      @event.end_time = modify_datetime(@event.end_time, allowed_timezone_params[:time_zone])
      if @event.save
        @event.guest_ids = allowed_guest_params[:guest_ids]
        flash[:notice] = 'Great! Your event has been created!'
        redirect_to :root
      else
        flash.now[:error] = 'Something\'s wrong. Can\'t create new event. Please check your input'
        render :new, status: :unprocessable_entity
      end
    end
  end

  def add_guest
    @event = Event.find(params[:id])
    if (@event.host.id == current_user.id)
      flash.now[:error] = 'You can\'t be a guest if you are the host of this event.'
      render :new, status: :unprocessable_entity
    elsif @event.guests.include?(current_user)
      flash.now[:error] = 'You have already joined.'
      render :new, status: :unprocessable_entity
    else
      @event.guests << current_user
      respond_to do |format|
        format.html { redirect_to request.referrer, notice: 'Great! You joined this event!' }
      end
    end
  end

  def remove_guest
    @event = Event.find(params[:id])
    if @event.guests.include?(current_user)
      @event.guests.delete(current_user)
      respond_to do |format|
        format.html { redirect_to request.referrer, notice: 'You left this event' }
      end
    else
      flash.now[:error] = 'Something\'s wrong. You are not part of this event.'
      render :new, status: :unprocessable_entity
    end
  end

  private

  def search_user_handler
    search_params = allowed_search_user_params

    if search_params[:query].present?
      @users = User.where('username like ?', "#{search_params[:query]}%").limit(10)
    else
      @users = User.none
    end

    if search_params[:query].present?
      respond_to do |format|
        format.turbo_stream
      end
    end
  end

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end

  def allowed_event_search_params
    params.permit(:search_name)
  end

  def allowed_event_params
    params.require(:event).permit(:name, :location, :start_time, :end_time, :note)
  end

  def allowed_timezone_params
    params.require(:event).permit(:time_zone)
  end

  def allowed_guest_params
    params.require(:event).permit(guest_ids: [])
  end

  def allowed_search_user_params
    params.permit(:id, :query, :turbo_frame, :turbo_action)
  end

  def modify_datetime(datetime, time_zone)
    d = datetime
    datetime.in_time_zone(time_zone)
            .change(year: d.year, month: d.month, day: d.day, hour: d.hour, min: d.min, sec: d.sec)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="card mb-3">
  <div class="card-body">
    <div class="d-flex justify-content-between">
      <div>
        <h3 class="card-title"><%= link_to event.name, event_path(event.id), class:"text-decoration-none "%></h3>
        <% if event.end_time < Time.now %>
          <span class="badge rounded-pill text-bg-warning">This event has ended</span>
        <% else %>
        <span class="badge rounded-pill text-bg-light">This event will start in <%= time_ago_in_words(event.start_time) %></span>
        <% end %>
      </div>
      <small class="text-secondary text-end" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="<%= event.created_at.localtime.strftime('%B %e, %Y at %l:%M %p') %>">created <%= time_ago_in_words(event.created_at) %> ago</small>
    </div>
    <p class="card-text">
      <p><span class="badge rounded-pill text-bg-light">Hosted by <%= link_to event.host.username, show_profile_path(event.host.username) %></span>
        <span class="badge rounded-pill text-bg-light"><i class="bi bi-geo-alt"></i> <%= event.location%></span></p>
      <p><span class="badge rounded-pill text-bg-light"><i class="bi bi-calendar-event"></i> Start: <%= event.start_time.localtime.strftime('%b %e, %Y at %l:%M %p (GMT%Z)') %> </span> <i class="bi bi-arrow-right"></i>
        <span class="badge rounded-pill text-bg-light"><i class="bi bi-calendar-event"></i> End: <%= event.end_time.localtime.strftime('%b %e, %Y at %l:%M %p (GMT%Z)')%> </span></p>
    </p>
  </div>
</div>

app/views/events/_guests.html.erb
<div class="dual-listbox event_guest_ids my-3">
  <div class="dual-listbox__container">
    <div>
      <input id="searchleft" class="dual-listbox__search form-control" placeholder="Search username">
      <div class="dual-listbox__title text-secondary mt-3">Username search result</div>
      <div id="username-list">
        <%= form.collection_select :user_search, {}, {}, {}, {}, { :multiple => true, :size => 10, class: "form-select" } %>
      </div>
    </div>
    <div class="dual-listbox__buttons">
      <button id="addbtn" type="button" class="dual-listbox__button btn btn-primary m-2">&gt;</button>
      <button id="removebtn" type="button" class="dual-listbox__button btn btn-primary m-2">&lt;</button>
      <button id="removeAllbtn" type="button" class="dual-listbox__button btn btn-primary m-2">&lt;&lt;</button>
    </div>
    <div data-controller="guest-filter">
      <input id="searchright" class="dual-listbox__search form-control" placeholder="Search guest" data-action="input->guest-filter#filter" data-guest-filter-target="source">
      <div class="dual-listbox__title text-secondary mt-3">Guests included in this event</div>
      <div id="guest-selected">
      <%= form.collection_select :guest_ids, @event.guests, :id, :username, {}, { :multiple => true, :size => 10, class: "form-select", data: {"guest-filter-target": "filterable"} } %>
      </div>
  </div>
</div>

app/views/events/edit.html.erb
<%= content_for :addscript do %>
  <%= javascript_import_module_tag "dual-listbox/dual-listbox" %>
<% end %>
<main>
  <div class="card mx-auto my-4" style="width: 50rem;">
    <div class="card-body">
      <h3 class="card-title text-center" id="editEventTitle">Create new event</h3>
      <p class="card-text">
        <% if @event.errors.any? %>
          <div id="error_explanation alert alert-warning alert-dismissible fade show" role="alert">
            <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being created:</h2>
            <ul>
              <% @event.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>
        <p>Hosted by: <%= link_to current_user.username, show_profile_path(current_user.username) %>
          <%= form_with model: @event, local: true, html: { method: :put, id: "event-form" } do |form| %>
            <div class="field mb-4">
              <%= form.label :name, class: "form-label" %><br />
              <%= form.text_field :name, class:"form-control"%>
            </div>
            <div class="field mb-4">
              <%= form.label :location, class: "form-label" %><br />
              <%= form.text_field :location, class:"form-control"%>
            </div>
            <div data-controller="timezone">
            <div class="row g-2">
              <div class="col-md">
                <div class="field mb-4">
                  <%= form.label :start_time, class: "form-label" %><br />
                  <%= form.datetime_field :start_time, class:"form-control", data: {"timezone-target": "startTimeInput", "action": "input->timezone#show_start_time_info"}, value: @event.start_time.localtime.strftime("%Y-%m-%dT%H:%M") %>
                  <small id="show_start_time" class="text-secondary" data-timezone-target="startTimeText"></small>
                </div>
              </div>
              <div class="col-md">
                <div class="field mb-4">
                  <%= form.label :end_time, class: "form-label" %><br />
                  <%= form.datetime_field :end_time, class:"form-control", data: {"timezone-target": "endTimeInput", "action": "input->timezone#show_end_time_info"}, value: @event.end_time.localtime.strftime("%Y-%m-%dT%H:%M")%>
                  <small id="show_end_time" class="text-secondary" data-timezone-target="endTimeText"></small>
                </div>
              </div>
            </div>
            <div class="field mb-4">
              <%= form.label :time_zone, class: "form-label" %><br />
              <%= form.select :time_zone, ActiveSupport::TimeZone.all.collect {|tz| ["(GMT#{ActiveSupport::TimeZone.seconds_to_utc_offset(tz.utc_offset)}) #{tz.name}", tz.tzinfo.name]}, {}, {class: "form-select","data-timezone-target": "timezoneSelect"} %>
            </div>
            </div>
            <div class="field mb-4">
              <%= form.label :note, class: "form-label" %><br />
              <%= form.text_area :note, placeholder: "Additional note", class:"form-control"%>
            </div>
            <div class="field mb-4">
              <%= form.label :guests, class: "form-label" %><br />
              <%= render partial: "events/guests", formats: [:html], :locals => {:guests =>  @event.guests, :form => form} %>
            </div>
            <div class="actions d-grid gap-2 col-12 mx-auto mb-4">
              <%= form.submit "Update this event", class:"btn btn-primary d-md-block" %>
            </div>
          <% end %>
        </p>
      </div>
    </div>
  </main>

app/views/events/edit.turbo_stream.erb
<turbo-stream action="replace" target="username-list">
  <template id="username-list-template">
    <div id="username-list" data-controller="username-list">
      <%= form_with model: @event, local: true, html: { method: :put } do |form| %>
        <%= form.collection_select :user_search, @users, :id, :username, {}, { :multiple => true, :size => 10, class: "form-select", data: {"username-list-target": "filterable"} } %>
      <%end%>
    </div>
  </template>
</turbo-stream>

app/views/events/index.html.erb
<%= content_for :addscript do %>
  <%= javascript_import_module_tag "custom-scripts/tooltip" %>
<% end %>
<div class="container my-2">
  <div class="row">
    <div class="col-md-9">
      <%= render @events %>
    </div>
    <div class="col-md-3">
      <div class="p-5 mb-2 bg-light rounded-2">
        <p>Create an event now</p>
        <%= link_to "Create new event", new_event_path, class: "btn btn-outline-primary p-2" %>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<%= content_for :addscript do %>
  <%= javascript_import_module_tag "dual-listbox/dual-listbox" %>
<% end %>
<main>
  <div class="card mx-auto my-4" style="width: 50rem;">
    <div class="card-body">
      <h3 class="card-title text-center" id="newEventTitle">Create new event</h3>
      <p class="card-text">
        <% if @event.errors.any? %>
          <div id="error_explanation alert alert-warning alert-dismissible fade show" role="alert">
            <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being created:</h2>
            <ul>
              <% @event.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>
        <p>Hosted by: <%= link_to current_user.username, show_profile_path(current_user.username) %>
          <%= form_with model: @event, local: true, html: { method: :post, id: "event-form" } do |form| %>
            <div class="field mb-4">
              <%= form.label :name, class: "form-label" %><br />
              <%= form.text_field :name, placeholder: "Event's name", class:"form-control"%>
            </div>
            <div class="field mb-4">
              <%= form.label :location, class: "form-label" %><br />
              <%= form.text_field :location, placeholder: "Location", class:"form-control"%>
            </div>
            <div data-controller="timezone">
              <div class="row g-2">
                <div class="col-md">
                  <div class="field mb-4">
                    <%= form.label :start_time, class: "form-label" %><br />
                    <%= form.datetime_field :start_time, class:"form-control", data: {"timezone-target": "startTimeInput", "action": "input->timezone#show_start_time_info"}, value: Time.now.strftime("%Y-%m-%dT%H:%M") %>
                    <small id="show_start_time" class="text-secondary" data-timezone-target="startTimeText"></small>
                  </div>
                </div>
                <div class="col-md">
                  <div class="field mb-4">
                    <%= form.label :end_time, class: "form-label" %><br />
                    <%= form.datetime_field :end_time, class:"form-control", data: {"timezone-target": "endTimeInput", "action": "input->timezone#show_end_time_info"}, value: Time.now.strftime("%Y-%m-%dT%H:%M")%>
                    <small id="show_end_time" class="text-secondary" data-timezone-target="endTimeText"></small>
                  </div>
                </div>
              </div>
              <div class="field mb-4">
                <%= form.label :time_zone, class: "form-label" %><br />
                <%= form.select :time_zone, ActiveSupport::TimeZone.all.collect {|tz| ["(GMT#{ActiveSupport::TimeZone.seconds_to_utc_offset(tz.utc_offset)}) #{tz.name}", tz.tzinfo.name]}, {}, {class: "form-select","data-timezone-target": "timezoneSelect"} %>
              </div>
            </div>
            <div class="field mb-4">
              <%= form.label :note, class: "form-label" %><br />
              <%= form.text_area :note, placeholder: "Additional note", class:"form-control"%>
            </div>
            <div class="field mb-4">
              <%= form.label :guests, class: "form-label" %><br />
              <%= render partial: "events/guests", formats: [:html], :locals => {:guests =>  @event.guests, :form => form} %>
            </div>
            <div class="actions d-grid gap-2 col-12 mx-auto mb-4">
              <%= form.submit "Add new event", class:"btn btn-primary d-md-block" %>
            </div>
          <% end %>
        </p>
      </div>
    </div>
  </main>

app/views/events/new.turbo_stream.erb
<turbo-stream action="replace" target="username-list">
  <template id="username-list-template">
    <div id="username-list" data-controller="username-list">
      <%= form_with model: @event, local: true, html: { method: :post} do |form| %>
        <%= form.collection_select :user_search, @users, :id, :username, {}, { :multiple => true, :size => 10, class: "form-select", data: {"username-list-target": "filterable"} } %>
      <%end%>
    </div>
  </template>
</turbo-stream>

app/views/events/show.html.erb
<%= content_for :addscript do %>
  <%= javascript_import_module_tag "custom-scripts/tooltip" %>
<% end %>
<div class="container my-2">
  <div class="row mb-3">
    <div class="col-md-9">
      <h1 class="card-title"><%= @event.name %></h1>
      <small class="text-secondary text-end" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="<%= @event.created_at.localtime.strftime('%B %e, %Y at %l:%M %p') %>">This event is created <%= time_ago_in_words(@event.created_at) %> ago</small>
    </div>
    <div class="col-md-3">
      <% if @event.host.id == current_user.id%>
        <div class="vstack gap-2">
          <%= link_to 'Edit this event', edit_event_path(@event.id), class: 'btn btn-primary' %>
          <%= button_to 'Delete this event', @event,  method: :delete, form: { data: { turbo_confirm: 'Are you sure you want to delete this event?' } }, class: 'btn btn-danger w-100' %>
        </div>
      <% else %>
        <% if @event.guests.include?(current_user)%>
          <%= button_to 'Leave this event', remove_guest_path(@event.id), class: 'btn btn-danger mx-2 w-100', :method => :delete %>
        <% else%>
          <%= button_to 'Join this event', add_guest_path(@event.id), class: 'btn btn-primary mx-2 w-100', :method => :post %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-9">
      <div class="card mb-3">
        <div class="card-body">
          <p class="card-text">
            <table class="table">
              <tbody>
                <tr>
                  <th scope="row">Host</th>
                  <td><%= link_to @event.host.username, show_profile_path(@event.host.username) %></td>
                </tr>
                <tr>
                  <th scope="row">Location</th>
                  <td><%= @event.location%></td>
                </tr>
                <tr>
                  <th scope="row" class="text-nowrap">Time start</th>
                  <td><%= @event.start_time.localtime.strftime('%A, %B %e, %Y at %l:%M %p (GMT%Z)') %> </td>
                </tr>
                <tr>
                  <th scope="row" class="text-nowrap"> Time end</th>
                  <td><%= @event.end_time.localtime.strftime('%A, %B %e, %Y at %l:%M %p (GMT%Z)')%> </td>
                </tr>
                <tr>
                  <th scope="row" class="text-nowrap">Guest list</th>
                  <td><%= safe_join(@event.guests.pluck(:username).map { |u| link_to(u, show_profile_path(u)) }, ", ".html_safe) %> </td>
                </tr>
                <tr>
                  <th scope="row">Note</th>
                  <td><%= @event.note %></td>
                </tr>
              </tbody>
            </table>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>